services:
  todo-db:
    image: postgres:16-alpine
    container_name: todo-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: TodoDb
    ports:
      - "5432:5432"
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    networks:
      - todo-network

  todo-api:
    image: todo-webapi
    container_name: todo-dotnet-api
    build:
      context: .
      dockerfile: TodoApp.WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=todo-db;Port=5432;Database=TodoDb;Username=postgres;Password=your_secure_password
    depends_on:
      - todo-db
    networks:
      - todo-network

volumes:
  todo-db-data:

networks:
  todo-network:
    driver: bridge